"""Localization for CodeSaver's command-line interface.

Translations live in code so the installed package remains self-contained and
does not need a separate runtime data directory. The public helpers are small
enough to be reused by integrations that want to select a language explicitly.
"""

from __future__ import annotations

import locale
import os
from typing import Any, Mapping, Optional

SUPPORTED_LANGUAGES = ("ru", "uk", "en", "de", "fr", "es", "pt", "zh", "ja", "ko", "hi", "ar")
DEFAULT_LANGUAGE = "en"

LANGUAGE_NAMES = {
    "ru": "Русский",
    "uk": "Українська",
    "en": "English",
    "de": "Deutsch",
    "fr": "Français",
    "es": "Español",
    "pt": "Português",
    "zh": "中文",
    "ja": "日本語",
    "ko": "한국어",
    "hi": "हिन्दी",
    "ar": "العربية",
}


TRANSLATIONS: Mapping[str, Mapping[str, str]] = {
    "en": {
        "help.description": "Automatic ZIP backups for a code project",
        "help.project_dir": "Project directory to back up",
        "help.backup_dir": "Directory where ZIP backups are stored",
        "help.interval": "Autosave interval in seconds (default: 600)",
        "help.no_autosave": "Disable the background autosave thread",
        "help.backup_now": "Create one backup and exit",
        "help.restore": "Restore an archive and exit",
        "help.overwrite": "Allow restore to replace existing files",
        "help.language": "Interface language (default: detected from system locale)",
        "help.language_choices": "language code",
        "arg.usage": "usage:",
        "arg.options": "options",
        "arg.positional": "positional arguments",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. Create backup",
        "menu.restore": "  2. Restore from backup",
        "menu.exit": "  3. Exit",
        "prompt.choice": "Choose an action: ",
        "prompt.archive": "Path to ZIP archive: ",
        "message.autosave_enabled": "Background autosave enabled: every {interval} seconds",
        "message.backup_created": "Backup created: {path}",
        "message.restore_completed": "Files restored: {count}",
        "message.autosave_created": "[autosave] Backup created: {path}",
        "message.autosave_error": "[autosave] Error: {error}",
        "message.invalid_choice": "Enter 1, 2, or 3.",
        "message.stopping": "Stopping CodeSaver...",
        "message.error": "Error: {error}",
        "errors.interval_positive": "Autosave interval must be greater than zero",
        "errors.project_missing": "Project directory does not exist: {project}",
        "errors.project_not_dir": "Project path is not a directory: {project}",
        "errors.archive_missing": "Backup archive does not exist: {archive}",
        "errors.file_exists": "File already exists (use --overwrite): {path}",
        "errors.unsafe_path": "Unsafe path in archive: {member}",
        "errors.create_failed": "Could not create backup: {error}",
        "errors.restore_failed": "Could not restore backup: {error}",
    },
    "ru": {
        "help.description": "Автоматические ZIP-бэкапы проекта с исходным кодом",
        "help.project_dir": "Директория проекта для резервного копирования",
        "help.backup_dir": "Директория для хранения ZIP-бэкапов",
        "help.interval": "Интервал автосохранения в секундах (по умолчанию: 600)",
        "help.no_autosave": "Отключить фоновое автосохранение",
        "help.backup_now": "Создать один бэкап и завершить работу",
        "help.restore": "Восстановить архив и завершить работу",
        "help.overwrite": "Разрешить замену существующих файлов",
        "help.language": "Язык интерфейса (по умолчанию определяется по локали системы)",
        "help.language_choices": "код языка",
        "arg.usage": "использование:",
        "arg.options": "параметры",
        "arg.positional": "позиционные аргументы",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. Сделать бэкап",
        "menu.restore": "  2. Восстановить из бэкапа",
        "menu.exit": "  3. Выход",
        "prompt.choice": "Выберите действие: ",
        "prompt.archive": "Путь к ZIP-архиву: ",
        "message.autosave_enabled": "Фоновое автосохранение включено: каждые {interval} сек.",
        "message.backup_created": "Бэкап создан: {path}",
        "message.restore_completed": "Восстановлено файлов: {count}",
        "message.autosave_created": "[автосохранение] Бэкап создан: {path}",
        "message.autosave_error": "[автосохранение] Ошибка: {error}",
        "message.invalid_choice": "Введите 1, 2 или 3.",
        "message.stopping": "CodeSaver завершает работу...",
        "message.error": "Ошибка: {error}",
        "errors.interval_positive": "Интервал автосохранения должен быть больше нуля",
        "errors.project_missing": "Директория проекта не существует: {project}",
        "errors.project_not_dir": "Путь проекта не является директорией: {project}",
        "errors.archive_missing": "Архив бэкапа не существует: {archive}",
        "errors.file_exists": "Файл уже существует (используйте --overwrite): {path}",
        "errors.unsafe_path": "Небезопасный путь в архиве: {member}",
        "errors.create_failed": "Не удалось создать бэкап: {error}",
        "errors.restore_failed": "Не удалось восстановить бэкап: {error}",
    },
    "uk": {
        "help.description": "Автоматичні ZIP-резервні копії проєкту з кодом",
        "help.project_dir": "Каталог проєкту для резервного копіювання",
        "help.backup_dir": "Каталог для ZIP-резервних копій",
        "help.interval": "Інтервал автозбереження в секундах (типово: 600)",
        "help.no_autosave": "Вимкнути фонове автозбереження",
        "help.backup_now": "Створити одну копію та завершити роботу",
        "help.restore": "Відновити архів і завершити роботу",
        "help.overwrite": "Дозволити заміну наявних файлів",
        "help.language": "Мова інтерфейсу (типово визначається локаллю системи)",
        "help.language_choices": "код мови",
        "arg.usage": "використання:",
        "arg.options": "параметри",
        "arg.positional": "позиційні аргументи",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. Створити резервну копію",
        "menu.restore": "  2. Відновити з копії",
        "menu.exit": "  3. Вихід",
        "prompt.choice": "Оберіть дію: ",
        "prompt.archive": "Шлях до ZIP-архіву: ",
        "message.autosave_enabled": "Фонове автозбереження увімкнено: кожні {interval} с",
        "message.backup_created": "Резервну копію створено: {path}",
        "message.restore_completed": "Відновлено файлів: {count}",
        "message.autosave_created": "[автозбереження] Копію створено: {path}",
        "message.autosave_error": "[автозбереження] Помилка: {error}",
        "message.invalid_choice": "Введіть 1, 2 або 3.",
        "message.stopping": "CodeSaver завершує роботу...",
        "message.error": "Помилка: {error}",
        "errors.interval_positive": "Інтервал автозбереження має бути більшим за нуль",
        "errors.project_missing": "Каталог проєкту не існує: {project}",
        "errors.project_not_dir": "Шлях проєкту не є каталогом: {project}",
        "errors.archive_missing": "Архів резервної копії не існує: {archive}",
        "errors.file_exists": "Файл уже існує (використайте --overwrite): {path}",
        "errors.unsafe_path": "Небезпечний шлях в архіві: {member}",
        "errors.create_failed": "Не вдалося створити резервну копію: {error}",
        "errors.restore_failed": "Не вдалося відновити резервну копію: {error}",
    },
    "de": {
        "help.description": "Automatische ZIP-Sicherungen für ein Codeprojekt",
        "help.project_dir": "Zu sicherndes Projektverzeichnis",
        "help.backup_dir": "Verzeichnis für ZIP-Sicherungen",
        "help.interval": "Intervall der automatischen Sicherung in Sekunden (Standard: 600)",
        "help.no_autosave": "Automatische Hintergrundsicherung deaktivieren",
        "help.backup_now": "Eine Sicherung erstellen und beenden",
        "help.restore": "Ein Archiv wiederherstellen und beenden",
        "help.overwrite": "Ersetzen vorhandener Dateien erlauben",
        "help.language": "Oberflächensprache (wird standardmäßig aus der System-Locale erkannt)",
        "help.language_choices": "Sprachcode",
        "arg.usage": "verwendung:",
        "arg.options": "optionen",
        "arg.positional": "positionsargumente",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. Sicherung erstellen",
        "menu.restore": "  2. Aus Sicherung wiederherstellen",
        "menu.exit": "  3. Beenden",
        "prompt.choice": "Aktion auswählen: ",
        "prompt.archive": "Pfad zum ZIP-Archiv: ",
        "message.autosave_enabled": "Automatische Hintergrundsicherung aktiv: alle {interval} Sekunden",
        "message.backup_created": "Sicherung erstellt: {path}",
        "message.restore_completed": "Wiederhergestellte Dateien: {count}",
        "message.autosave_created": "[automatisch] Sicherung erstellt: {path}",
        "message.autosave_error": "[automatisch] Fehler: {error}",
        "message.invalid_choice": "Geben Sie 1, 2 oder 3 ein.",
        "message.stopping": "CodeSaver wird beendet...",
        "message.error": "Fehler: {error}",
        "errors.interval_positive": "Das Sicherungsintervall muss größer als null sein",
        "errors.project_missing": "Projektverzeichnis nicht gefunden: {project}",
        "errors.project_not_dir": "Projektpfad ist kein Verzeichnis: {project}",
        "errors.archive_missing": "Sicherungsarchiv nicht gefunden: {archive}",
        "errors.file_exists": "Datei existiert bereits (--overwrite verwenden): {path}",
        "errors.unsafe_path": "Unsicherer Pfad im Archiv: {member}",
        "errors.create_failed": "Sicherung konnte nicht erstellt werden: {error}",
        "errors.restore_failed": "Sicherung konnte nicht wiederhergestellt werden: {error}",
    },
    "fr": {
        "help.description": "Sauvegardes ZIP automatiques pour un projet de code",
        "help.project_dir": "Répertoire du projet à sauvegarder",
        "help.backup_dir": "Répertoire de stockage des sauvegardes ZIP",
        "help.interval": "Intervalle de sauvegarde automatique en secondes (par défaut : 600)",
        "help.no_autosave": "Désactiver la sauvegarde automatique en arrière-plan",
        "help.backup_now": "Créer une sauvegarde puis quitter",
        "help.restore": "Restaurer une archive puis quitter",
        "help.overwrite": "Autoriser le remplacement des fichiers existants",
        "help.language": "Langue de l’interface (détectée depuis la locale du système par défaut)",
        "help.language_choices": "code langue",
        "arg.usage": "utilisation :",
        "arg.options": "options",
        "arg.positional": "arguments positionnels",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. Créer une sauvegarde",
        "menu.restore": "  2. Restaurer une sauvegarde",
        "menu.exit": "  3. Quitter",
        "prompt.choice": "Choisissez une action : ",
        "prompt.archive": "Chemin de l’archive ZIP : ",
        "message.autosave_enabled": "Sauvegarde automatique activée : toutes les {interval} secondes",
        "message.backup_created": "Sauvegarde créée : {path}",
        "message.restore_completed": "Fichiers restaurés : {count}",
        "message.autosave_created": "[automatique] Sauvegarde créée : {path}",
        "message.autosave_error": "[automatique] Erreur : {error}",
        "message.invalid_choice": "Saisissez 1, 2 ou 3.",
        "message.stopping": "Arrêt de CodeSaver...",
        "message.error": "Erreur : {error}",
        "errors.interval_positive": "L’intervalle doit être supérieur à zéro",
        "errors.project_missing": "Le répertoire du projet n’existe pas : {project}",
        "errors.project_not_dir": "Le chemin du projet n’est pas un répertoire : {project}",
        "errors.archive_missing": "L’archive de sauvegarde n’existe pas : {archive}",
        "errors.file_exists": "Le fichier existe déjà (utilisez --overwrite) : {path}",
        "errors.unsafe_path": "Chemin non sûr dans l’archive : {member}",
        "errors.create_failed": "Impossible de créer la sauvegarde : {error}",
        "errors.restore_failed": "Impossible de restaurer la sauvegarde : {error}",
    },
    "es": {
        "help.description": "Copias de seguridad ZIP automáticas para un proyecto de código",
        "help.project_dir": "Directorio del proyecto que se copiará",
        "help.backup_dir": "Directorio donde se guardan las copias ZIP",
        "help.interval": "Intervalo de copia automática en segundos (predeterminado: 600)",
        "help.no_autosave": "Desactivar la copia automática en segundo plano",
        "help.backup_now": "Crear una copia y salir",
        "help.restore": "Restaurar un archivo y salir",
        "help.overwrite": "Permitir reemplazar archivos existentes",
        "help.language": "Idioma de la interfaz (se detecta de la configuración regional del sistema)",
        "help.language_choices": "código de idioma",
        "arg.usage": "uso:",
        "arg.options": "opciones",
        "arg.positional": "argumentos posicionales",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. Crear copia de seguridad",
        "menu.restore": "  2. Restaurar desde una copia",
        "menu.exit": "  3. Salir",
        "prompt.choice": "Elige una acción: ",
        "prompt.archive": "Ruta del archivo ZIP: ",
        "message.autosave_enabled": "Copia automática activada: cada {interval} segundos",
        "message.backup_created": "Copia creada: {path}",
        "message.restore_completed": "Archivos restaurados: {count}",
        "message.autosave_created": "[automática] Copia creada: {path}",
        "message.autosave_error": "[automática] Error: {error}",
        "message.invalid_choice": "Introduce 1, 2 o 3.",
        "message.stopping": "CodeSaver se está cerrando...",
        "message.error": "Error: {error}",
        "errors.interval_positive": "El intervalo debe ser mayor que cero",
        "errors.project_missing": "El directorio del proyecto no existe: {project}",
        "errors.project_not_dir": "La ruta del proyecto no es un directorio: {project}",
        "errors.archive_missing": "El archivo de copia no existe: {archive}",
        "errors.file_exists": "El archivo ya existe (usa --overwrite): {path}",
        "errors.unsafe_path": "Ruta insegura en el archivo: {member}",
        "errors.create_failed": "No se pudo crear la copia: {error}",
        "errors.restore_failed": "No se pudo restaurar la copia: {error}",
    },
    "pt": {
        "help.description": "Backups ZIP automáticos para um projeto de código",
        "help.project_dir": "Diretório do projeto para backup",
        "help.backup_dir": "Diretório onde os backups ZIP são armazenados",
        "help.interval": "Intervalo do backup automático em segundos (padrão: 600)",
        "help.no_autosave": "Desativar o backup automático em segundo plano",
        "help.backup_now": "Criar um backup e sair",
        "help.restore": "Restaurar um arquivo e sair",
        "help.overwrite": "Permitir substituir arquivos existentes",
        "help.language": "Idioma da interface (detectado pela localidade do sistema)",
        "help.language_choices": "código do idioma",
        "arg.usage": "uso:",
        "arg.options": "opções",
        "arg.positional": "argumentos posicionais",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. Criar backup",
        "menu.restore": "  2. Restaurar do backup",
        "menu.exit": "  3. Sair",
        "prompt.choice": "Escolha uma ação: ",
        "prompt.archive": "Caminho do arquivo ZIP: ",
        "message.autosave_enabled": "Backup automático ativado: a cada {interval} segundos",
        "message.backup_created": "Backup criado: {path}",
        "message.restore_completed": "Arquivos restaurados: {count}",
        "message.autosave_created": "[automático] Backup criado: {path}",
        "message.autosave_error": "[automático] Erro: {error}",
        "message.invalid_choice": "Digite 1, 2 ou 3.",
        "message.stopping": "Encerrando o CodeSaver...",
        "message.error": "Erro: {error}",
        "errors.interval_positive": "O intervalo deve ser maior que zero",
        "errors.project_missing": "O diretório do projeto não existe: {project}",
        "errors.project_not_dir": "O caminho do projeto não é um diretório: {project}",
        "errors.archive_missing": "O arquivo de backup não existe: {archive}",
        "errors.file_exists": "O arquivo já existe (use --overwrite): {path}",
        "errors.unsafe_path": "Caminho inseguro no arquivo: {member}",
        "errors.create_failed": "Não foi possível criar o backup: {error}",
        "errors.restore_failed": "Não foi possível restaurar o backup: {error}",
    },
    "zh": {
        "help.description": "为代码项目自动创建 ZIP 备份",
        "help.project_dir": "要备份的项目目录",
        "help.backup_dir": "ZIP 备份的存储目录",
        "help.interval": "自动保存间隔（秒，默认：600）",
        "help.no_autosave": "禁用后台自动保存",
        "help.backup_now": "创建一次备份后退出",
        "help.restore": "恢复备份后退出",
        "help.overwrite": "允许恢复时替换现有文件",
        "help.language": "界面语言（默认根据系统区域设置自动检测）",
        "help.language_choices": "语言代码",
        "arg.usage": "用法：",
        "arg.options": "选项",
        "arg.positional": "位置参数",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. 创建备份",
        "menu.restore": "  2. 从备份恢复",
        "menu.exit": "  3. 退出",
        "prompt.choice": "请选择操作：",
        "prompt.archive": "ZIP 文件路径：",
        "message.autosave_enabled": "后台自动保存已启用：每 {interval} 秒一次",
        "message.backup_created": "备份已创建：{path}",
        "message.restore_completed": "已恢复文件数：{count}",
        "message.autosave_created": "[自动保存] 备份已创建：{path}",
        "message.autosave_error": "[自动保存] 错误：{error}",
        "message.invalid_choice": "请输入 1、2 或 3。",
        "message.stopping": "CodeSaver 正在退出……",
        "message.error": "错误：{error}",
        "errors.interval_positive": "自动保存间隔必须大于零",
        "errors.project_missing": "项目目录不存在：{project}",
        "errors.project_not_dir": "项目路径不是目录：{project}",
        "errors.archive_missing": "备份文件不存在：{archive}",
        "errors.file_exists": "文件已存在（请使用 --overwrite）：{path}",
        "errors.unsafe_path": "备份中存在不安全路径：{member}",
        "errors.create_failed": "无法创建备份：{error}",
        "errors.restore_failed": "无法恢复备份：{error}",
    },
    "ja": {
        "help.description": "コードプロジェクト用の自動 ZIP バックアップ",
        "help.project_dir": "バックアップするプロジェクトディレクトリ",
        "help.backup_dir": "ZIP バックアップの保存先",
        "help.interval": "自動保存の間隔（秒、既定値: 600）",
        "help.no_autosave": "バックグラウンド自動保存を無効にする",
        "help.backup_now": "バックアップを1つ作成して終了する",
        "help.restore": "アーカイブを復元して終了する",
        "help.overwrite": "既存ファイルの置き換えを許可する",
        "help.language": "インターフェース言語（既定ではシステムのロケールから検出）",
        "help.language_choices": "言語コード",
        "arg.usage": "使い方:",
        "arg.options": "オプション",
        "arg.positional": "位置引数",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. バックアップを作成",
        "menu.restore": "  2. バックアップから復元",
        "menu.exit": "  3. 終了",
        "prompt.choice": "操作を選択してください: ",
        "prompt.archive": "ZIP アーカイブのパス: ",
        "message.autosave_enabled": "バックグラウンド自動保存が有効です: {interval} 秒ごと",
        "message.backup_created": "バックアップを作成しました: {path}",
        "message.restore_completed": "復元したファイル数: {count}",
        "message.autosave_created": "[自動保存] バックアップを作成しました: {path}",
        "message.autosave_error": "[自動保存] エラー: {error}",
        "message.invalid_choice": "1、2、3 のいずれかを入力してください。",
        "message.stopping": "CodeSaver を終了しています...",
        "message.error": "エラー: {error}",
        "errors.interval_positive": "自動保存の間隔は0より大きくしてください",
        "errors.project_missing": "プロジェクトディレクトリが存在しません: {project}",
        "errors.project_not_dir": "プロジェクトパスはディレクトリではありません: {project}",
        "errors.archive_missing": "バックアップアーカイブが存在しません: {archive}",
        "errors.file_exists": "ファイルは既に存在します（--overwrite を使用）: {path}",
        "errors.unsafe_path": "アーカイブ内に安全でないパスがあります: {member}",
        "errors.create_failed": "バックアップを作成できませんでした: {error}",
        "errors.restore_failed": "バックアップを復元できませんでした: {error}",
    },
    "ko": {
        "help.description": "코드 프로젝트를 위한 자동 ZIP 백업",
        "help.project_dir": "백업할 프로젝트 디렉터리",
        "help.backup_dir": "ZIP 백업 저장 디렉터리",
        "help.interval": "자동 저장 간격(초, 기본값: 600)",
        "help.no_autosave": "백그라운드 자동 저장 비활성화",
        "help.backup_now": "백업 하나를 만들고 종료",
        "help.restore": "아카이브를 복원하고 종료",
        "help.overwrite": "기존 파일을 덮어쓰도록 허용",
        "help.language": "인터페이스 언어(기본값은 시스템 로케일에서 감지)",
        "help.language_choices": "언어 코드",
        "arg.usage": "사용법:",
        "arg.options": "옵션",
        "arg.positional": "위치 인수",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. 백업 만들기",
        "menu.restore": "  2. 백업에서 복원",
        "menu.exit": "  3. 종료",
        "prompt.choice": "작업을 선택하세요: ",
        "prompt.archive": "ZIP 아카이브 경로: ",
        "message.autosave_enabled": "백그라운드 자동 저장 사용: {interval}초마다",
        "message.backup_created": "백업 생성 완료: {path}",
        "message.restore_completed": "복원된 파일 수: {count}",
        "message.autosave_created": "[자동 저장] 백업 생성 완료: {path}",
        "message.autosave_error": "[자동 저장] 오류: {error}",
        "message.invalid_choice": "1, 2 또는 3을 입력하세요.",
        "message.stopping": "CodeSaver를 종료합니다...",
        "message.error": "오류: {error}",
        "errors.interval_positive": "자동 저장 간격은 0보다 커야 합니다",
        "errors.project_missing": "프로젝트 디렉터리가 없습니다: {project}",
        "errors.project_not_dir": "프로젝트 경로가 디렉터리가 아닙니다: {project}",
        "errors.archive_missing": "백업 아카이브가 없습니다: {archive}",
        "errors.file_exists": "파일이 이미 있습니다(--overwrite 사용): {path}",
        "errors.unsafe_path": "아카이브에 안전하지 않은 경로가 있습니다: {member}",
        "errors.create_failed": "백업을 만들 수 없습니다: {error}",
        "errors.restore_failed": "백업을 복원할 수 없습니다: {error}",
    },
    "hi": {
        "help.description": "कोड प्रोजेक्ट के लिए स्वचालित ZIP बैकअप",
        "help.project_dir": "बैकअप के लिए प्रोजेक्ट डायरेक्टरी",
        "help.backup_dir": "ZIP बैकअप रखने की डायरेक्टरी",
        "help.interval": "ऑटोसेव अंतराल सेकंड में (डिफ़ॉल्ट: 600)",
        "help.no_autosave": "बैकग्राउंड ऑटोसेव बंद करें",
        "help.backup_now": "एक बैकअप बनाकर बाहर निकलें",
        "help.restore": "आर्काइव पुनर्स्थापित करके बाहर निकलें",
        "help.overwrite": "मौजूदा फ़ाइलों को बदलने की अनुमति दें",
        "help.language": "इंटरफ़ेस भाषा (डिफ़ॉल्ट रूप से सिस्टम locale से पता लगती है)",
        "help.language_choices": "भाषा कोड",
        "arg.usage": "उपयोग:",
        "arg.options": "विकल्प",
        "arg.positional": "पोज़िशनल आर्ग्युमेंट",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. बैकअप बनाएँ",
        "menu.restore": "  2. बैकअप से पुनर्स्थापित करें",
        "menu.exit": "  3. बाहर निकलें",
        "prompt.choice": "कार्य चुनें: ",
        "prompt.archive": "ZIP आर्काइव का पथ: ",
        "message.autosave_enabled": "बैकग्राउंड ऑटोसेव चालू है: हर {interval} सेकंड",
        "message.backup_created": "बैकअप बनाया गया: {path}",
        "message.restore_completed": "पुनर्स्थापित फ़ाइलें: {count}",
        "message.autosave_created": "[ऑटोसेव] बैकअप बनाया गया: {path}",
        "message.autosave_error": "[ऑटोसेव] त्रुटि: {error}",
        "message.invalid_choice": "1, 2 या 3 दर्ज करें।",
        "message.stopping": "CodeSaver बंद हो रहा है...",
        "message.error": "त्रुटि: {error}",
        "errors.interval_positive": "ऑटोसेव अंतराल शून्य से अधिक होना चाहिए",
        "errors.project_missing": "प्रोजेक्ट डायरेक्टरी मौजूद नहीं है: {project}",
        "errors.project_not_dir": "प्रोजेक्ट पथ डायरेक्टरी नहीं है: {project}",
        "errors.archive_missing": "बैकअप आर्काइव मौजूद नहीं है: {archive}",
        "errors.file_exists": "फ़ाइल पहले से मौजूद है (--overwrite का उपयोग करें): {path}",
        "errors.unsafe_path": "आर्काइव में असुरक्षित पथ है: {member}",
        "errors.create_failed": "बैकअप नहीं बनाया जा सका: {error}",
        "errors.restore_failed": "बैकअप पुनर्स्थापित नहीं किया जा सका: {error}",
    },
    "ar": {
        "help.description": "نسخ احتياطية تلقائية بصيغة ZIP لمشروع برمجي",
        "help.project_dir": "مجلد المشروع المراد نسخه احتياطياً",
        "help.backup_dir": "مجلد تخزين النسخ الاحتياطية",
        "help.interval": "الفاصل الزمني للحفظ التلقائي بالثواني (الافتراضي: 600)",
        "help.no_autosave": "تعطيل الحفظ التلقائي في الخلفية",
        "help.backup_now": "إنشاء نسخة احتياطية واحدة والخروج",
        "help.restore": "استعادة أرشيف والخروج",
        "help.overwrite": "السماح باستبدال الملفات الموجودة",
        "help.language": "لغة الواجهة (تُكتشف تلقائياً من إعدادات المنطقة)",
        "help.language_choices": "رمز اللغة",
        "arg.usage": "الاستخدام:",
        "arg.options": "الخيارات",
        "arg.positional": "المعاملات الموضعية",
        "menu.header": "CodeSaver",
        "menu.backup": "  1. إنشاء نسخة احتياطية",
        "menu.restore": "  2. الاستعادة من نسخة احتياطية",
        "menu.exit": "  3. خروج",
        "prompt.choice": "اختر إجراءً: ",
        "prompt.archive": "مسار أرشيف ZIP: ",
        "message.autosave_enabled": "تم تفعيل الحفظ التلقائي: كل {interval} ثانية",
        "message.backup_created": "تم إنشاء النسخة الاحتياطية: {path}",
        "message.restore_completed": "عدد الملفات المستعادة: {count}",
        "message.autosave_created": "[حفظ تلقائي] تم إنشاء النسخة: {path}",
        "message.autosave_error": "[حفظ تلقائي] خطأ: {error}",
        "message.invalid_choice": "أدخل 1 أو 2 أو 3.",
        "message.stopping": "جارٍ إيقاف CodeSaver...",
        "message.error": "خطأ: {error}",
        "errors.interval_positive": "يجب أن يكون الفاصل الزمني أكبر من صفر",
        "errors.project_missing": "مجلد المشروع غير موجود: {project}",
        "errors.project_not_dir": "مسار المشروع ليس مجلداً: {project}",
        "errors.archive_missing": "أرشيف النسخة الاحتياطية غير موجود: {archive}",
        "errors.file_exists": "الملف موجود بالفعل (استخدم --overwrite): {path}",
        "errors.unsafe_path": "مسار غير آمن داخل الأرشيف: {member}",
        "errors.create_failed": "تعذر إنشاء النسخة الاحتياطية: {error}",
        "errors.restore_failed": "تعذرت استعادة النسخة الاحتياطية: {error}",
    },
}


_HELP_TEXT = {
    "en": "show this help message and exit",
    "ru": "показать эту справку и завершить работу",
    "uk": "показати цю довідку та завершити роботу",
    "de": "diese Hilfe anzeigen und beenden",
    "fr": "afficher cette aide et quitter",
    "es": "mostrar esta ayuda y salir",
    "pt": "mostrar esta ajuda e sair",
    "zh": "显示此帮助信息并退出",
    "ja": "このヘルプを表示して終了する",
    "ko": "이 도움말을 표시하고 종료",
    "hi": "यह सहायता संदेश दिखाएँ और बाहर निकलें",
    "ar": "عرض رسالة المساعدة هذه والخروج",
}
for _language, _text in _HELP_TEXT.items():
    TRANSLATIONS[_language]["help.help"] = _text


_EXTRA_TRANSLATIONS = {
    "en": {
        "help.config": "Path to a JSON configuration file",
        "help.log": "Write operation logs to this file",
        "message.progress": "Progress: {current}/{total} files ({percent:.0f}%)",
        "errors.config_not_found": "Configuration file does not exist: {path}",
        "errors.config_invalid": "Invalid configuration file {path}: {error}",
        "errors.config_value": "Invalid configuration value: {key}",
        "errors.invalid_zip": "The ZIP archive is damaged: {archive}",
        "errors.permission": "Permission denied while accessing: {path}",
        "errors.log_failed": "Could not open log file: {error}",
        "errors.python_version": "CodeSaver requires Python 3.9 or newer; detected Python {version}",
    },
    "ru": {
        "help.config": "Путь к JSON-файлу конфигурации",
        "help.log": "Сохранять логи операций в этот файл",
        "message.progress": "Прогресс: {current}/{total} файлов ({percent:.0f}%)",
        "errors.config_not_found": "Файл конфигурации не существует: {path}",
        "errors.config_invalid": "Некорректный файл конфигурации {path}: {error}",
        "errors.config_value": "Некорректное значение конфигурации: {key}",
        "errors.invalid_zip": "ZIP-архив повреждён: {archive}",
        "errors.permission": "Нет прав доступа при обращении к: {path}",
        "errors.log_failed": "Не удалось открыть файл лога: {error}",
        "errors.python_version": "Для CodeSaver требуется Python 3.9 или новее; обнаружен Python {version}",
    },
    "uk": {
        "help.config": "Шлях до JSON-файлу конфігурації",
        "help.log": "Зберігати журнали операцій у цей файл",
        "message.progress": "Прогрес: {current}/{total} файлів ({percent:.0f}%)",
        "errors.config_not_found": "Файл конфігурації не існує: {path}",
        "errors.config_invalid": "Некоректний файл конфігурації {path}: {error}",
        "errors.config_value": "Некоректне значення конфігурації: {key}",
        "errors.invalid_zip": "ZIP-архів пошкоджено: {archive}",
        "errors.permission": "Немає прав доступу до: {path}",
        "errors.log_failed": "Не вдалося відкрити файл журналу: {error}",
        "errors.python_version": "Для CodeSaver потрібен Python 3.9 або новіший; виявлено Python {version}",
    },
    "de": {
        "help.config": "Pfad zu einer JSON-Konfigurationsdatei",
        "help.log": "Operationsprotokoll in diese Datei schreiben",
        "message.progress": "Fortschritt: {current}/{total} Dateien ({percent:.0f}%)",
        "errors.config_not_found": "Konfigurationsdatei nicht gefunden: {path}",
        "errors.config_invalid": "Ungültige Konfigurationsdatei {path}: {error}",
        "errors.config_value": "Ungültiger Konfigurationswert: {key}",
        "errors.invalid_zip": "Das ZIP-Archiv ist beschädigt: {archive}",
        "errors.permission": "Zugriff verweigert: {path}",
        "errors.log_failed": "Protokolldatei konnte nicht geöffnet werden: {error}",
        "errors.python_version": "CodeSaver benötigt Python 3.9 oder neuer; erkannt wurde Python {version}",
    },
    "fr": {
        "help.config": "Chemin vers un fichier de configuration JSON",
        "help.log": "Enregistrer les opérations dans ce fichier",
        "message.progress": "Progression : {current}/{total} fichiers ({percent:.0f} %)",
        "errors.config_not_found": "Le fichier de configuration n’existe pas : {path}",
        "errors.config_invalid": "Fichier de configuration invalide {path} : {error}",
        "errors.config_value": "Valeur de configuration invalide : {key}",
        "errors.invalid_zip": "L’archive ZIP est endommagée : {archive}",
        "errors.permission": "Accès refusé : {path}",
        "errors.log_failed": "Impossible d’ouvrir le journal : {error}",
        "errors.python_version": (
            "CodeSaver nécessite Python 3.9 ou une version plus récente ; Python {version} détecté"
        ),
    },
    "es": {
        "help.config": "Ruta a un archivo de configuración JSON",
        "help.log": "Guardar el registro de operaciones en este archivo",
        "message.progress": "Progreso: {current}/{total} archivos ({percent:.0f}%)",
        "errors.config_not_found": "El archivo de configuración no existe: {path}",
        "errors.config_invalid": "Archivo de configuración no válido {path}: {error}",
        "errors.config_value": "Valor de configuración no válido: {key}",
        "errors.invalid_zip": "El archivo ZIP está dañado: {archive}",
        "errors.permission": "Permiso denegado al acceder a: {path}",
        "errors.log_failed": "No se pudo abrir el archivo de registro: {error}",
        "errors.python_version": "CodeSaver requiere Python 3.9 o posterior; se detectó Python {version}",
    },
    "pt": {
        "help.config": "Caminho para um arquivo de configuração JSON",
        "help.log": "Salvar o registro das operações neste arquivo",
        "message.progress": "Progresso: {current}/{total} arquivos ({percent:.0f}%)",
        "errors.config_not_found": "O arquivo de configuração não existe: {path}",
        "errors.config_invalid": "Arquivo de configuração inválido {path}: {error}",
        "errors.config_value": "Valor de configuração inválido: {key}",
        "errors.invalid_zip": "O arquivo ZIP está corrompido: {archive}",
        "errors.permission": "Permissão negada ao acessar: {path}",
        "errors.log_failed": "Não foi possível abrir o arquivo de log: {error}",
        "errors.python_version": "O CodeSaver requer Python 3.9 ou mais recente; Python {version} detectado",
    },
    "zh": {
        "help.config": "JSON 配置文件路径",
        "help.log": "将操作日志保存到此文件",
        "message.progress": "进度：{current}/{total} 个文件（{percent:.0f}%）",
        "errors.config_not_found": "配置文件不存在：{path}",
        "errors.config_invalid": "配置文件无效 {path}：{error}",
        "errors.config_value": "配置值无效：{key}",
        "errors.invalid_zip": "ZIP 压缩包已损坏：{archive}",
        "errors.permission": "没有访问权限：{path}",
        "errors.log_failed": "无法打开日志文件：{error}",
        "errors.python_version": "CodeSaver 需要 Python 3.9 或更高版本；检测到 Python {version}",
    },
    "ja": {
        "help.config": "JSON 設定ファイルのパス",
        "help.log": "操作ログをこのファイルに保存する",
        "message.progress": "進捗: {current}/{total} ファイル ({percent:.0f}%)",
        "errors.config_not_found": "設定ファイルが存在しません: {path}",
        "errors.config_invalid": "設定ファイルが不正です {path}: {error}",
        "errors.config_value": "設定値が不正です: {key}",
        "errors.invalid_zip": "ZIP アーカイブが破損しています: {archive}",
        "errors.permission": "アクセス権がありません: {path}",
        "errors.log_failed": "ログファイルを開けませんでした: {error}",
        "errors.python_version": "CodeSaver には Python 3.9 以降が必要です。検出されたバージョン: {version}",
    },
    "ko": {
        "help.config": "JSON 구성 파일 경로",
        "help.log": "작업 로그를 이 파일에 저장",
        "message.progress": "진행률: {current}/{total}개 파일 ({percent:.0f}%)",
        "errors.config_not_found": "구성 파일이 없습니다: {path}",
        "errors.config_invalid": "구성 파일이 올바르지 않습니다 {path}: {error}",
        "errors.config_value": "구성 값이 올바르지 않습니다: {key}",
        "errors.invalid_zip": "ZIP 아카이브가 손상되었습니다: {archive}",
        "errors.permission": "접근 권한이 없습니다: {path}",
        "errors.log_failed": "로그 파일을 열 수 없습니다: {error}",
        "errors.python_version": "CodeSaver에는 Python 3.9 이상이 필요합니다. 감지된 버전: {version}",
    },
    "hi": {
        "help.config": "JSON कॉन्फ़िगरेशन फ़ाइल का पथ",
        "help.log": "ऑपरेशन लॉग इस फ़ाइल में सहेजें",
        "message.progress": "प्रगति: {current}/{total} फ़ाइलें ({percent:.0f}%)",
        "errors.config_not_found": "कॉन्फ़िगरेशन फ़ाइल मौजूद नहीं है: {path}",
        "errors.config_invalid": "अमान्य कॉन्फ़िगरेशन फ़ाइल {path}: {error}",
        "errors.config_value": "अमान्य कॉन्फ़िगरेशन मान: {key}",
        "errors.invalid_zip": "ZIP आर्काइव खराब है: {archive}",
        "errors.permission": "पहुंच की अनुमति नहीं है: {path}",
        "errors.log_failed": "लॉग फ़ाइल नहीं खोली जा सकी: {error}",
        "errors.python_version": "CodeSaver के लिए Python 3.9 या नया आवश्यक है; Python {version} मिला",
    },
    "ar": {
        "help.config": "مسار ملف إعدادات JSON",
        "help.log": "حفظ سجلات العمليات في هذا الملف",
        "message.progress": "التقدم: {current}/{total} ملفاً ({percent:.0f}٪)",
        "errors.config_not_found": "ملف الإعدادات غير موجود: {path}",
        "errors.config_invalid": "ملف الإعدادات غير صالح {path}: {error}",
        "errors.config_value": "قيمة إعدادات غير صالحة: {key}",
        "errors.invalid_zip": "أرشيف ZIP تالف: {archive}",
        "errors.permission": "تم رفض الإذن عند الوصول إلى: {path}",
        "errors.log_failed": "تعذر فتح ملف السجل: {error}",
        "errors.python_version": "يتطلب CodeSaver إصدار Python 3.9 أو أحدث؛ تم اكتشاف Python {version}",
    },
}
for _language, _messages in _EXTRA_TRANSLATIONS.items():
    TRANSLATIONS[_language].update(_messages)


_ALIASES = {
    "russian": "ru",
    "русский": "ru",
    "ukrainian": "uk",
    "українська": "uk",
    "english": "en",
    "german": "de",
    "deutsch": "de",
    "french": "fr",
    "spanish": "es",
    "portuguese": "pt",
    "chinese": "zh",
    "japanese": "ja",
    "korean": "ko",
    "hindi": "hi",
    "arabic": "ar",
}


def normalize_language(value: Optional[str]) -> str:
    """Return a supported two-letter language code for a locale-like value."""
    if not value:
        return DEFAULT_LANGUAGE
    normalized = value.strip().lower().replace("-", "_")
    if normalized in SUPPORTED_LANGUAGES:
        return normalized
    prefix = normalized.split("_")[0].split(".")[0]
    if prefix in SUPPORTED_LANGUAGES:
        return prefix
    return _ALIASES.get(prefix, DEFAULT_LANGUAGE)


def detect_language() -> str:
    """Detect the system language with a reliable English fallback."""
    for key in ("LC_ALL", "LC_MESSAGES", "LANG", "LANGUAGE"):
        value = os.environ.get(key)
        if value:
            return normalize_language(value.split(":")[0])
    try:
        language, _encoding = locale.getlocale()
    except (ValueError, AttributeError):
        language = None
    return normalize_language(language)


def translate(key: str, language: Optional[str] = None, **values: Any) -> str:
    """Translate a message key and safely format its values."""
    code = normalize_language(language) if language else detect_language()
    template = TRANSLATIONS.get(code, TRANSLATIONS[DEFAULT_LANGUAGE]).get(key)
    if template is None:
        template = TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key)
    try:
        return template.format(**values)
    except (KeyError, ValueError):
        return template
